jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox-travis
        pip install coveralls
    - name: Run flake8 tests
      run: tox -e flake8
    - name: Run isort tests
      run: tox -e isort
    - name: Upload coverage to Coveralls
      if: success()
      run: |
        if [ -e .coverage ]; then coveralls; fi