name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.10']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --yes gcc python3-dev libsqlcipher-dev
        pip install -U pip
        pip install pycodestyle codecov pytest pytest-cov coverage
        pip install .

    - name: Lint with pycodestyle
      run: pycodestyle --exclude=venv,__pycache__ --ignore=E501 .

    - name: Test with pytest
      run: pytest --cov=.

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true