name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage nose coveralls pyflakes pycodestyle
    - name: Run tests
      run: coverage run --source=olefile -m nose tests
    - name: Upload coverage to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: coveralls
    - name: Coverage report
      run: coverage report
    - name: Lint with pyflakes
      run: pyflakes .
    - name: Lint with pycodestyle
      run: pycodestyle --statistics --count .