name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.8', '3.7', '3.6', 'nightly']
        include:
          - python-version: 'nightly'
            allow_failure: true
          - python-version: '3.7'
            allow_failure: true

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade setuptools pip
        pip install .
        pip install doit
        doit install_test_deps
    - name: Run tests
      run: doit test